import type {
  Store,
  StoreImage,
  StoreReport,
} from "@/lib/types";

export interface DemoDatabase {
  stores: Store[];
  storeImages: StoreImage[];
  storeReports: StoreReport[];
}

const now = "2026-03-08T04:00:00.000Z";

export const createDemoDatabase = (): DemoDatabase => ({
  stores: [
    {
      id: "store-seongsu",
      name: "버터하우스 성수",
      slug: "버터하우스-성수",
      summary: "짭짤한 버터떡과 라즈베리 쿠키가 인기인 성수동 디저트 숍",
      address: "서울특별시 성동구 연무장길 18 1층",
      sido: "서울특별시",
      sigungu: "성동구",
      latitude: 37.5444,
      longitude: 127.0557,
      phone: "02-543-1200",
      openingHours: "화-일 11:00-20:00",
      websiteUrl: "https://butterhouse.example.com",
      instagramUrl: "https://instagram.com/butterhouse.seongsu",
      kakaoMapUrl: "https://place.map.kakao.com/123456",
      naverMapUrl: "https://map.naver.com/p/entry/place/1234567890",
      googleMapUrl: "https://maps.app.goo.gl/exampleShareLink",
      status: "active",
      disabledReason: null,
      createdAt: "2026-02-20T02:00:00.000Z",
      updatedAt: "2026-02-20T02:00:00.000Z",
    },
    {
      id: "store-yeonnam",
      name: "말랑떡연구소 연남",
      slug: "말랑떡연구소-연남",
      summary: "매일 구운 쫀득 버터떡을 진열하는 연남동 작은 실험실",
      address: "서울특별시 마포구 동교로38길 24",
      sido: "서울특별시",
      sigungu: "마포구",
      latitude: 37.563,
      longitude: 126.9252,
      phone: "070-8812-4545",
      openingHours: "매일 12:00-21:00",
      websiteUrl: null,
      instagramUrl: "https://instagram.com/mallanglab",
      kakaoMapUrl: "https://place.map.kakao.com/234567",
      naverMapUrl: null,
      googleMapUrl: "https://maps.app.goo.gl/yeonnamShare",
      status: "active",
      disabledReason: null,
      createdAt: "2026-02-18T05:30:00.000Z",
      updatedAt: "2026-02-18T05:30:00.000Z",
    },
    {
      id: "store-busan",
      name: "우유버터공방 서면",
      slug: "우유버터공방-서면",
      summary: "부산 서면에서 크림버터떡과 계절 한정 메뉴를 파는 공방형 매장",
      address: "부산광역시 부산진구 전포대로199번길 26",
      sido: "부산광역시",
      sigungu: "부산진구",
      latitude: 35.1578,
      longitude: 129.0592,
      phone: "051-701-8881",
      openingHours: "수-월 11:30-20:30",
      websiteUrl: "https://milkbutter.example.com",
      instagramUrl: "https://instagram.com/milkbutter.lab",
      kakaoMapUrl: null,
      naverMapUrl: "https://map.naver.com/p/entry/place/2222222222",
      googleMapUrl: null,
      status: "active",
      disabledReason: null,
      createdAt: "2026-02-15T02:10:00.000Z",
      updatedAt: "2026-02-15T02:10:00.000Z",
    },
    {
      id: "store-gwanggyo",
      name: "구움떡집 광교",
      slug: "구움떡집-광교",
      summary: "광교 호수공원 근처에서 버터떡 샌드와 선물 세트를 만드는 베이크숍",
      address: "경기도 수원시 영통구 센트럴타운로 85",
      sido: "경기도",
      sigungu: "수원시 영통구",
      latitude: 37.2869,
      longitude: 127.0519,
      phone: "031-214-4407",
      openingHours: "매일 10:30-19:30",
      websiteUrl: null,
      instagramUrl: "https://instagram.com/gubteok.gwanggyo",
      kakaoMapUrl: null,
      naverMapUrl: null,
      googleMapUrl: null,
      status: "active",
      disabledReason: null,
      createdAt: "2026-02-13T04:40:00.000Z",
      updatedAt: "2026-02-13T04:40:00.000Z",
    },
    {
      id: "store-daejeon",
      name: "노른자버터방앗간 둔산",
      slug: "노른자버터방앗간-둔산",
      summary: "노란 버터크림과 쌀 디저트를 결합한 대전 둔산동 매장",
      address: "대전광역시 서구 둔산로31번길 28",
      sido: "대전광역시",
      sigungu: "서구",
      latitude: 36.3508,
      longitude: 127.3782,
      phone: "042-488-9031",
      openingHours: "화-일 11:00-20:00",
      websiteUrl: "https://yolkbakery.example.com",
      instagramUrl: null,
      kakaoMapUrl: null,
      naverMapUrl: null,
      googleMapUrl: "https://maps.app.goo.gl/daejeonShare",
      status: "active",
      disabledReason: null,
      createdAt: "2026-02-10T06:20:00.000Z",
      updatedAt: "2026-02-10T06:20:00.000Z",
    },
  ],
  storeImages: [
    {
      id: "img-seongsu-1",
      storeId: "store-seongsu",
      imageUrl: "/demo/store-seoul.svg",
      altText: "버터하우스 성수 대표 이미지",
      sortOrder: 0,
      createdAt: now,
    },
    {
      id: "img-seongsu-2",
      storeId: "store-seongsu",
      imageUrl: "/demo/store-detail-a.svg",
      altText: "버터하우스 성수 진열대 이미지",
      sortOrder: 1,
      createdAt: now,
    },
    {
      id: "img-yeonnam-1",
      storeId: "store-yeonnam",
      imageUrl: "/demo/store-coral.svg",
      altText: "말랑떡연구소 연남 대표 이미지",
      sortOrder: 0,
      createdAt: now,
    },
    {
      id: "img-busan-1",
      storeId: "store-busan",
      imageUrl: "/demo/store-ocean.svg",
      altText: "우유버터공방 서면 대표 이미지",
      sortOrder: 0,
      createdAt: now,
    },
    {
      id: "img-gwanggyo-1",
      storeId: "store-gwanggyo",
      imageUrl: "/demo/store-sun.svg",
      altText: "구움떡집 광교 대표 이미지",
      sortOrder: 0,
      createdAt: now,
    },
    {
      id: "img-daejeon-1",
      storeId: "store-daejeon",
      imageUrl: "/demo/store-cream.svg",
      altText: "노른자버터방앗간 둔산 대표 이미지",
      sortOrder: 0,
      createdAt: now,
    },
  ],
  storeReports: [
    {
      id: "report-yeonnam-1",
      storeId: "store-yeonnam",
      reportType: "wrong_info",
      note: "최근 방문했을 때 영업시간이 변경돼 있었습니다.",
      reporterName: "연남동 제보자",
      reporterContact: null,
      status: "pending",
      resolution: null,
      createdAt: "2026-03-05T06:15:00.000Z",
      reviewedAt: null,
    },
    {
      id: "report-busan-1",
      storeId: "store-busan",
      reportType: "closed",
      note: "이번 주에 방문했는데 임시 휴점 안내가 붙어 있었습니다.",
      reporterName: "부산 사용자",
      reporterContact: null,
      status: "pending",
      resolution: null,
      createdAt: "2026-03-06T07:00:00.000Z",
      reviewedAt: null,
    },
    {
      id: "report-busan-2",
      storeId: "store-busan",
      reportType: "wrong_info",
      note: "전화번호가 연결되지 않습니다.",
      reporterName: null,
      reporterContact: null,
      status: "pending",
      resolution: null,
      createdAt: "2026-03-07T09:00:00.000Z",
      reviewedAt: null,
    },
  ],
});
